API of the micro framework has changed.
Code remain like that should cause error as follow:
```
# command-line-arguments
token-service/main.go:26:25: cannot use []cli.Flag literal (type []cli.Flag) as type cli.Flag in argument to micro.Flags:
	[]cli.Flag does not implement cli.Flag (missing Apply method)
```